### ISSUE TITLE
Pick moderators

### ISSUE THREAD

**Issue by jni** [numfocus/scipy-2019-funding-foss-bof#1]
The BoF form requires nominating two moderators. I nominate @lsilen and @freeman-lab, but I'm very happy for anyone else to come forward!

I also made the choice of suggesting the format as open discussion vs panel discussion because I would like to hear from everyone invited, which is already big, but also from others who would be interested I have surely missed.

**Comment by jni** [comment]
@aterrel as you can see, the repo has been moved under numfocus. It's also public now. (side note: I was surprised to see that numfocus doesn't have a pro github account!)

**Comment by jni** [comment]
Incidentally I no longer seem to have admin access... =)

**Comment by aterrel** [comment]
Sorry I’ll fix that. And right no pro account, Github is our public place.

Did @lsilen agree to moderate?

**Comment by jni** [comment]
> Did @lsilen agree to moderate?

Not to my knowledge. =)

**Comment by lsilen** [comment]
Happy to moderate if still needed.


---
Leah Silen
Executive Director, NumFOCUS
leah@numfocus.org
512-831-2870

<http://www.numfocus.org/>
<https://twitter.com/NumFOCUS>
<https://www.facebook.com/NumFOCUS/>

**Comment by jni** [comment]
@lsilen based on the above thread, it is doubly needed! =P

@freeman-lab, would you be interested in moderating with @lsilen?

**Comment by rgommers** [comment]
Since @jni's just asked in another issue: I volunteer to moderate.
